name: Deploy salary-day-reminder to AWS Lambda

on:
  push:
    branches: [ "main" ]
    paths: [ "salary-day-reminder/**" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.1.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy Lambda Function
      uses: aws-actions/aws-lambda-deploy@v1.1.2
      with:
        function-name: salary-day-reminder
        code-artifacts-dir: salary-day-reminder
        handler: ${{ vars.LAMBDA_HANDLER }}
        runtime: ${{ vars.LAMBDA_RUNTIME }}
